name: Trigger auto deployment for dwittechwalletservicewebapi-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/dwittechwalletservicewebapi-app-AutoDeployTrigger-70dcc669-c3d7-4e0d-9f81-8c63da175708.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: dotnetcoreapi20230130123723.azurecr.io
          username: ${{ secrets.DWITTECHWALLETSERVICEWEBAPIAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.DWITTECHWALLETSERVICEWEBAPIAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dotnetcoreapi20230130123723.azurecr.io/dwittechwalletservicewebapi-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DWITTECHWALLETSERVICEWEBAPIAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n dwittechwalletservicewebapi-app -g dwit-tech --server dotnetcoreapi20230130123723.azurecr.io --username  ${{ secrets.DWITTECHWALLETSERVICEWEBAPIAPP_REGISTRY_USERNAME }} --password ${{ secrets.DWITTECHWALLETSERVICEWEBAPIAPP_REGISTRY_PASSWORD }}
            az containerapp update -n dwittechwalletservicewebapi-app -g dwit-tech --image dotnetcoreapi20230130123723.azurecr.io/dwittechwalletservicewebapi-app:${{ github.sha }}
